### ISSUE TITLE
More Information about Requisites to Work

### ISSUE THREAD

**Issue by nuninhoneto** [TheHorscht/FmodBankGUIDReplacer#1]
Does it work with which fmod version? Could be used with master banks or just slave?

I tried with a master bank and it didnt work. Fmod version 2.01.07

**Comment by TheHorscht** [comment]
I've only tested it with `2.01.05`, does it find the GUIDs if you run it just by passing in the bank file?
`guid_replacer.exe "Master Bank.bank"`

**Comment by nuninhoneto** [comment]
Unfortunately nothings :(

![image](https://github.com/TheHorscht/FmodBankGUIDReplacer/assets/6090462/d7e384ba-8692-4847-8043-a19825c249c1)

**Comment by TheHorscht** [comment]
Huh, nothing at all? That's weird. Does it have sounds inside and assigned to a bank? Can you upload the bank file here maybe so I can try and see if it works on my computer?

**Comment by nuninhoneto** [comment]
Yes, there are one event and one sound attached. 

If it would be not too much to ask, Could you please provide an email so its safer for me to send you the file?

**Comment by TheHorscht** [comment]
Sure, I'm gonna post it as an image because I don't know if any bots scrawl for email addresses and spam me to death. (Even though emails should be publicly available in the commit history 🤷‍♂️ )
![image](https://github.com/TheHorscht/FmodBankGUIDReplacer/assets/11724363/621957cb-eacc-4201-b24c-c7995c1d2448)

**Comment by nuninhoneto** [comment]
I sent the files by email. Thanks in advance.

**Comment by TheHorscht** [comment]
Hmm it works fine for me:
![image](https://github.com/TheHorscht/FmodBankGUIDReplacer/assets/11724363/e60b1196-321b-434a-8d91-30b73d275f07)
So it's not an issue with your bank files. I'm not sure what's wrong, I rarely use C++

**Comment by TheHorscht** [comment]
I also tried it on my laptop with a fresh install of windows 10, so I don't think it requires installing any extra runtimes. Does it at least display some info on how to use it if you don't specify anything at all? Just:
`> guid_replacer.exe`

**Comment by nuninhoneto** [comment]
I'm using the release build hosted here. i'm not compiling the code and executing.

I saw in code main.cpp that line 208 is commented, so i think that is the problem.

![image](https://github.com/TheHorscht/FmodBankGUIDReplacer/assets/6090462/468c0228-46fd-4eb8-9f9a-c64257f8d7a6)

If it isnt a problem, could you try to replace master bus to another guid? The master bus guid is {bdf392c2-cf3d-4c31-b7d2-f2c6adfb0582}. On my tests, i couldn't replace it with your tool.

**Comment by TheHorscht** [comment]
Oh... right, idk why that's commented out in the executable I provided 😬 It's been a while and I think no one has really used it yet and noticed the mistake.
Try it with the new version I just uploaded (https://github.com/TheHorscht/FmodBankGUIDReplacer/releases/tag/v0.1.1). It should give you an output like:
`Found a GUID at offset 628 - {6118bf3c-8fe8-435f-ad00-67927dbb0567} - 3cbf1861e88f5f43ad0067927dbb0567`
So then you take that GUID in the brackets and run it again:
`> guid_replacer.exe "Slave.bank" {6118bf3c-8fe8-435f-ad00-67927dbb0567} {here-what-to-replace-it-with}`

**Comment by TheHorscht** [comment]
Closing this because it was mostly a misunderstanding, my program can't replace bus GUIDs, only event GUIDs, clarified it in the README.md
